development:
  # adapter: async
  adapter: redis
  url: redis://127.0.0.1:6379
  channel_prefix: crowtits_development
  timeout: 10


test:
  adapter: async

production:
  adapter: redis
  url: redis://127.0.0.1:6379
  channel_prefix: crowtits_production
  timeout: 10
