development:
  # adapter: async
  adapter: redis
  url: redis://127.0.0.1:6379


test:
  # adapter: async
  adapter: redis
  url: redis://127.0.0.1:6379


production:
  adapter: redis
  url: redis://127.0.0.1:6379
  channel_prefix: crowtits_production
  timeout: 10
